#!/bin/bash
#===============================================================================
# generate-inventory.sh — Generate Ansible inventory.ini from Terraform output
#===============================================================================
# Reads Terraform outputs (rtx_node, rk3576_node, network_vlans) and generates
# a valid Ansible inventory.ini for the home-cluster.
#
# Usage:
#   cd terraform && terraform output --json | ../scripts/generate-inventory.sh
#   ./scripts/generate-inventory.sh --dry-run
#   ./scripts/generate-inventory.sh --output ansible/inventory.ini
#===============================================================================

set -euo pipefail

INVENTORY_FILE="${INVENTORY_FILE:-ansible/inventory.ini}"
DRY_RUN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    --output) INVENTORY_FILE="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Fetch Terraform outputs as JSON (pipe mode: reads from stdin)
if [[ -t 0 ]]; then
  # No pipe — try terraform directly
  TERRAFORM_OUTPUT=$(terraform output --json 2>/dev/null) || {
    echo "[ERROR] No Terraform output found. Run 'terraform output --json' or pipe JSON to stdin." >&2
    exit 1
  }
else
  # Pipe mode — read from stdin
  TERRAFORM_OUTPUT=$(cat -)
fi

if [[ -z "$TERRAFORM_OUTPUT" ]]; then
  echo "[ERROR] Empty Terraform output." >&2
  exit 1
fi

# Extract values using jq
# ── RTX Primary Node ──
RTX_HOSTNAME=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.hostname // empty')
RTX_MGMT=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.mgmt_ip // empty')
RTX_COMPUTE=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.compute_ip // empty')
RTX_STORAGE=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.storage_ip // empty')
RTX_VPN=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.vpn_ip // empty')
RTX_GPU_COUNT=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.gpu_count // "0"')
RTX_GPU_NAME=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rtx_node.value.gpu_name // "unknown"')

# ── RK3576 Edge Node ──
RK_HOSTNAME=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rk3576_node.value.hostname // empty')
RK_MGMT=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rk3576_node.value.mgmt_ip // empty')
RK_COMPUTE=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rk3576_node.value.compute_ip // empty')
RK_VPN=$(echo "$TERRAFORM_OUTPUT" | jq -r '.rk3576_node.value.vpn_ip // empty')

# ── VLANs ──
VLAN_MGMT=$(echo "$TERRAFORM_OUTPUT" | jq -r '.network_vlans.value.mgmt // empty')
VLAN_COMPUTE=$(echo "$TERRAFORM_OUTPUT" | jq -r '.network_vlans.value.compute // empty')
VLAN_STORAGE=$(echo "$TERRAFORM_OUTPUT" | jq -r '.network_vlans.value.storage // empty')
VLAN_VPN=$(echo "$TERRAFORM_OUTPUT" | jq -r '.network_vlans.value.vpn // empty')

# ── Slurm ──
SLURM_CLUSTER=$(echo "$TERRAFORM_OUTPUT" | jq -r '.slurm_endpoints.value.cluster_name // "home-cluster"')
SLURM_CONTROL=$(echo "$TERRAFORM_OUTPUT" | jq -r '.slurm_endpoints.value.control_host // empty')

# Validate at least one node
if [[ -z "$RTX_HOSTNAME" ]] && [[ -z "$RK_HOSTNAME" ]]; then
  echo "[ERROR] No nodes found in Terraform output (check rtx_node / rk3576_node)." >&2
  exit 1
fi

# ── Defaults ──
RTX_HOSTNAME="${RTX_HOSTNAME:-rtx-node}"
RTX_MGMT="${RTX_MGMT:-192.168.20.10}"
RTX_COMPUTE="${RTX_COMPUTE:-192.168.20.10}"
RTX_STORAGE="${RTX_STORAGE:-192.168.30.10}"
RTX_VPN="${RTX_VPN:-10.200.0.10}"
RK_HOSTNAME="${RK_HOSTNAME:-rk3576-node}"
RK_MGMT="${RK_MGMT:-192.168.20.11}"
RK_COMPUTE="${RK_COMPUTE:-192.168.20.11}"
RK_VPN="${RK_VPN:-10.200.0.11}"
VLAN_MGMT="${VLAN_MGMT:-192.168.10.0/24}"
VLAN_COMPUTE="${VLAN_COMPUTE:-192.168.20.0/24}"
VLAN_STORAGE="${VLAN_STORAGE:-192.168.30.0/24}"
VLAN_VPN="${VLAN_VPN:-10.200.0.0/16}"

# ── Generate inventory.ini ──
mkdir -p "$(dirname "$INVENTORY_FILE")"

cat > "${INVENTORY_FILE}.tmp" << EOF
# =============================================================================
# INVENTORY — Auto-generated by scripts/generate-inventory.sh
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source: Terraform outputs (terraform output --json)
# =============================================================================
# IMPORTANT: Review all IPs before running Ansible!
# =============================================================================

[primary]
${RTX_HOSTNAME}  ansible_host=${RTX_MGMT}

[edge]
${RK_HOSTNAME}  ansible_host=${RK_MGMT}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=root
# ansible_ssh_private_key_file=~/.ssh/home-cluster
# ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[primary:vars]
rtx_gpu_count=${RTX_GPU_COUNT}
rtx_gpu_model=${RTX_GPU_NAME}
rtx_ip_mgmt=${RTX_MGMT}
rtx_ip_compute=${RTX_COMPUTE}
rtx_ip_storage=${RTX_STORAGE}
rtx_ip_vpn=${RTX_VPN}
slurm_cluster=${SLURM_CLUSTER}
slurm_control_host=${SLURM_CONTROL:-${RTX_MGMT}}

[edge:vars]
rk_ip_mgmt=${RK_MGMT}
rk_ip_compute=${RK_COMPUTE}
rk_ip_vpn=${RK_VPN}

[vlans:children]
primary
edge

[vlans:vars]
vlan_mgmt=${VLAN_MGMT}
vlan_compute=${VLAN_COMPUTE}
vlan_storage=${VLAN_STORAGE}
vlan_vpn=${VLAN_VPN}
EOF

if [[ "$DRY_RUN" == true ]]; then
  echo "[DRY RUN] Would write to $INVENTORY_FILE:"
  cat "${INVENTORY_FILE}.tmp"
  rm "${INVENTORY_FILE}.tmp"
else
  mv "${INVENTORY_FILE}.tmp" "$INVENTORY_FILE"
  echo "[OK] Generated $INVENTORY_FILE"
  echo "     Run: ansible-inventory -i $INVENTORY_FILE --list"
fi
