version: '3.8'

services:
  perses:
    image: persesdev/perses:v0.49.0
    container_name: acos_perses
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./perses_config:/perses/config:ro
      - ./dashboards:/etc/perses/dashboards:ro
      - perses_data:/perses/data
    command: --config.file=/perses/config/perses.yaml
    networks:
      - perses_net

networks:
  perses_net:
    driver: bridge

volumes:
  perses_data:
