apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"

  - name: Ceph
    type: prometheus
    access: proxy
    url: http://10.30.30.10:9283
    editable: false
