# =============================================================================
# HOME CLUSTER IAAC — TERRAFORM MAIN
# =============================================================================
# Provisions:
#   - MikroTik router (via API/SSH)
#   - Network inventory (hosts file)
#   - WireGuard mesh config generator
#   - Ceph inventory
#   - Slurm inventory
# =============================================================================

terraform {
  required_version = ">= 1.5"
  required_providers {
    local   = { source = "hashicorp/local" }
    null    = { source = "hashicorp/null" }
  }
}

provider "local" {}

# =============================================================================
# DATA — read Ansible inventory template
# =============================================================================

data "template_file" "inventory_template" {
  template = file("${path.module}/templates/inventory.ini.tpl")
  vars = {
    rtx_ip      = var.rtx_node.ip_compute
    rk3576_ip   = var.rk3576_node.ip_compute
    vps_ip      = var.vps_node.enabled ? var.vps_node.ip_vpn : ""
    cluster_name = var.cluster_name
  }
}

# =============================================================================
# RESOURCES
# =============================================================================

resource "local_file" "ansible_inventory" {
  content  = data.template_file.inventory_template.rendered
  filename = "${path.module}/../ansible/inventory.ini"
}

resource "local_file" "hosts_file" {
  content  = <<-EOF
# Cluster hosts — generated by Terraform
[rtx_node]
${var.rtx_node.ip_compute} hostname=${var.rtx_node.hostname}

[rk3576_node]
${var.rk3576_node.ip_compute} hostname=${var.rk3576_node.hostname}

${var.vps_node.enabled ? <<-EOS
[vps_node]
${var.vps_node.ip_vpn} hostname=${var.vps_node.hostname}
EOS : ""}

[all:vars]
cluster_name=${var.cluster_name}
ansible_user=root
EOF
  filename = "${path.module}/hosts"
}

resource "local_file" "wireguard_mesh_conf" {
  content = <<-EOF
# WireGuard mesh config — generated by Terraform
# Copy relevant [Peer] sections to each node's /etc/wireguard/wg0.conf

[Interface]
Address = ${var.rtx_node.ip_vpn}/24
ListenPort = ${var.wireguard.listen_port}
PrivateKey = <RTX_NODE_PRIVATE_KEY>

[Peer]
# RK3576
PublicKey = <RK3576_PUBLIC_KEY>
AllowedIPs = ${var.rk3576_node.ip_vpn}/32
Endpoint = ${var.rk3576_node.ip_mgmt}:${var.wireguard.listen_port}
PersistentKeepalive = 25

${var.vps_node.enabled ? <<-EOS
[Peer]
# VPS
PublicKey = <VPS_PUBLIC_KEY>
AllowedIPs = ${var.vps_node.ip_vpn}/32
Endpoint = ${var.vps_node.public_ip}:${var.wireguard.listen_port}
PersistentKeepalive = 25
EOS : ""}
EOF
  filename = "${path.module}/wireguard_mesh.conf"
}

resource "local_file" "slurm_conf" {
  content = <<-EOF
# Slurm configuration — generated by Terraform
ClusterName=${var.slurm.cluster_name}
ControlMachine=${var.slurm.control_node}
SlurmUser=slurm
StateSaveLocation=/var/spool/slurm
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm
TmpFS=/tmp
# GPUs
GresTypes=gpu

# Nodes
NodeName=${var.rtx_node.hostname} NodeAddr=${var.rtx_node.ip_compute} ${var.rtx_node.cpu_cores} State=UNKNOWN
NodeName=${var.rk3576_node.hostname} NodeAddr=${var.rk3576_node.ip_compute} ${var.rk3576_node.cpu_cores} State=UNKNOWN

# Partitions
PartitionName=${var.slurm.gpu_partition} Nodes=${var.rtx_node.hostname} Default=YES MaxTime=INFINITE State=UP
PartitionName=${var.slurm.cpu_partition} Nodes=${var.rk3576_node.hostname} MaxTime=INFINITE State=UP
EOF
  filename = "${path.module}/slurm.conf"
}

resource "null_resource" "mikrotik_provision" {
  # MikroTik provisioning via API ( RouterOS 7 )
  # Requires: curl + RouterOS API access
  triggers = {
    mikrotik_ip = var.mikrotik.ip_mgmt
  }
  provisioner "local-exec" {
    command = <<-EOS
    echo "MikroTik provision: use ansible/roles/mikrotik/"
    echo "Or manually: ssh ${var.mikrotik.ssh_user}@${var.mikrotik.ip_mgmt}"
    EOS
  }
}
