jwt:
    secret: ENC[AES256_GCM,data:w6ANcvSQ3H8ISi9j8T2oBmORmvLCgxG4XQUVHKLSgssUUVlfo+8qt1BM9SnRJvjmnGmNckVhCM28RyBECbOyQhtZEwbnxmWlxRieRkRMwvZvvjvBDbk=,iv:UPL6Z70Mot60t8GsUWthPDjISp+q9XdVSUCyvLuGhcg=,tag:YDGL5I9cZPRp9gn0dnN24g==,type:str]
    access_ttl_min: ENC[AES256_GCM,data:ah8=,iv:CGv1dSVLI1+FBWPpiqixR66GWbHQSIvU5MucfsVBG4c=,tag:6pcg6MkQ2oumJcgHGkzUtQ==,type:int]
    refresh_ttl_days: ENC[AES256_GCM,data:8g==,iv:icVrjJmSELQqZpiU6z/YZ7+csvE+zuSrgDjC9tVV1Xw=,tag:BCfIJ1ocCbARSzhITb4DIA==,type:int]
    algorithm: ENC[AES256_GCM,data:VvefBx8=,iv:IsyxxZ+9EBzVvUlbx3q9HWQQm7VsyQiPYxGeQYTJ1ps=,tag:uNldoNNl8LsMuFkudfN80A==,type:str]
dev_users:
    - username: ENC[AES256_GCM,data:T3SNm0Y=,iv:ozf0gcKmR4XMTZHjURmHDaY4jeZHDXwSQz8GWW5LLtA=,tag:43Q6WBueaLIVTXubGSbRIg==,type:str]
      password_hash: ENC[AES256_GCM,data:mlAsi6gVeHgWZzc4wXQNT5o2mIxJEyLB93hGOXXcyIuG3Tb4IGHK9F95UpkkzVfq5fHznxaFv4QKd7m4,iv:IIXnyqzNug7+w8CqQJoIar0NDKLP5lr1qEILt0zIyWo=,tag:LNr6cp0YYfm/wBtnDC6wfg==,type:str]
sops:
    age:
        - recipient: age1c9ufnx2advuvf04atd2kluxhxkca8jw2j7r7d9mmwr75w5tm839q5q7s5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdnduSFIzOUFoWDVSd0h2
            MGFsaTM0NnlNS0ozbXBtVGRSd2x0blBqVzNZCjlPYmVyZzhIS3ZMcDlhNmZ2NmZU
            ZFdHejBCSGN3RDVxTjNDbEpjQ1cveUkKLS0tIG05dUp5UkxLQ1dDQnNqelh1eGp0
            OG00WEhVSzVZd28wZ1c3Zkt2MEhuTGcK4DaPQOZZ3gjRlDvnGcG1n7jXjC83qMSp
            /TPtBWZ8WS1VjSlytYZQ+M/VvHpK3N7AuWxjL4Dvghh4sH2+SRN2RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T10:57:17Z"
    mac: ENC[AES256_GCM,data:AgbI2dwoOYiCeDOD9oFEQOA8TK4k5xb6cT67i8i2B9ABfIHcSSSsADK41nZ03dyE0lqpuzzU8sPnUuuD0ZAEcvsk7sXP3uqK1eajMn3+LWEd6ZsnwE3S6pYrBYiZG9PtivsMIzlWGhRNFuOpXIXJAQBm6heoNZRju7X319PwirI=,iv:cQl+dh5wlSb25rkNgOtZsd1y1Hz4n7mKDkSPmozqNZQ=,tag:7yvDY7U1vchf7WpV5Dr+dQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
