jwt:
    secret: ENC[AES256_GCM,data:oD+VOAIJY06OQCvZ6YI3t1fRP/cbdBaRuojNaT1Zaf/HTDpP62+aUXrAmSSAbX59UR1fgge0XwPxWvZXC9YjCZNEKf4eau2AhJSFyKddfFLlPX449+I=,iv:fI4nWJUEwXQlmxHXTeWKcChj3aUnU+xttDxSBN+Eg/s=,tag:vYM6tz3j3Qcvycdsk5brAw==,type:str]
    access_ttl_min: ENC[AES256_GCM,data:fDM=,iv:PUl+RtsNMWWpRZdd/L9rsxz+N1mHGPI8BfrMqp/mQeU=,tag:oPclOEkm2MWL7D7Lhwabqw==,type:int]
    refresh_ttl_days: ENC[AES256_GCM,data:Qg==,iv:eTwT63GV4RoouclwPBAvfFveg/1JZI0umkmpKsiksHc=,tag:l81zYcPXEKp2/D5WVABUxg==,type:int]
    algorithm: ENC[AES256_GCM,data:Bvvkl5w=,iv:L8rCVjPCj67Q4MgDxjySTrY8Fe0XfjJFRFwcnPPd0o0=,tag:u0WWgBHSh/W4Gd75xkLqHA==,type:str]
dev_users:
    - username: ENC[AES256_GCM,data:77PfvYQ=,iv:0Iq/omCrrR0q2KrYK3tUAlbhqo7XjG9emh1g+f5voB0=,tag:wNEE5zy6rbBQgjUvrbqggQ==,type:str]
      role: ENC[AES256_GCM,data:nyJ98f0=,iv:+UQHesiIistSxQBXx5MbOHRjSQBPJTpJloLTyIyuP9c=,tag:ZO6NpnfkTzm4YthI83ny/g==,type:str]
      password_hash: ENC[AES256_GCM,data:AIZ6eaOkaIlxUv8GXCmiOZV3wEVqLnQX/Fmn+fsCZOpRqiamgvVE636pzMJcKJitGJoevwMR3dE+XXcx,iv:xetIATpt13zNC3Eh8brOS8lMaqdnM9zu6vrJk77aorM=,tag:SlOlCiYHgoO9ZDANBOpVrg==,type:str]
    - username: ENC[AES256_GCM,data:5hPdrAKA,iv:XtSFNAlrA5kWgJRNbBdFTq/XoaggM8mEqwgG/psFqtM=,tag:LMPA/X6VafbNiK35lgKYzw==,type:str]
      role: ENC[AES256_GCM,data:OL+UevXO,iv:DeAOO+JeLJkDhN0al6c3SF6cd9wo4sftD6xhdNH68KI=,tag:5/bnS5o5meUhSTsUm69u/w==,type:str]
      #ENC[AES256_GCM,data:pAWFiQs7LhdF/kuhOrNrkIROUQYllHez,iv:arOajus+lOSFOcSXz9aCWfcTyMr+tGqoJzpc0m8JGqU=,tag:zOw2ZBUBw6cG1l7p+WY+8A==,type:comment]
      password_hash: ENC[AES256_GCM,data:eKUM5pzipI7egKinmlOuYkCwS1ufBgmLEMH2GsYugerj0A9DAckePQ5D+mIXeRuE3pYC1fGEejkeLKFR,iv:mzWNQWPFiC12AjOCEyPGbiqYC8J0oIjHX2tXSXIoGK8=,tag:VPT4QXOZlZ3RrsyztEY7tg==,type:str]
sops:
    age:
        - recipient: age1c9ufnx2advuvf04atd2kluxhxkca8jw2j7r7d9mmwr75w5tm839q5q7s5h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUFQ5LzNzanJyTHIxL3A0
            bXdsUnJ6RG1WRlAxNkNNVi9INks4YzZtaWdJCi9pWjhBcVdIakwwN0c0cVZic2RK
            S0luQWZmWjF4a0VUVUVhYUpwNGNkckUKLS0tIGJuZTJuR1pPeTdUa1ZvWndqTU5U
            TUdnOGk5L2QxYTRBTlNmNkJnVmZxOHMKAiLVlFNwg3HuxI+AAmpT3nMA1PwnC9XO
            H85oAPSs+MjWnUoC0tdcpWhYAAg9a9+g8ty+fy6d4wDkB8od6H0mqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T12:26:47Z"
    mac: ENC[AES256_GCM,data:qtDmtngmVI52rW74mzGIhzOA0mtVutmOVRL4+Mu5DaoO8xb1rKj6yhP/rzyPSIdYLZxNQm3ZfDafpMPvMuKFcdz5EftIZc3MFxBnajhZD4CDrwUm7qAlsFvHumO06hR3Q6I8Wq4tfpUHNe02W3Pc0Ad7PeceiN8F3Kkl7Ro/QxY=,iv:hUGS1RidHLsgsc8S+9EcZCdDckU8F14Gqziy1S87iro=,tag:t3gFCqA7SZzGPbYke20/Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
