# WireGuard/AmneziaWG VPN Mesh Module
# Generates peer configs for all cluster nodes

variable "cluster_name" { type = string }
variable "nodes" {
  type = map(object({
    role       = string
    ip         = string
    gpu        = bool
    cpu_cores  = number
    memory_gb  = number
  }))
}
variable "network_cidr"  { type = string }
variable "wireguard_port" {
  type    = number
  default = 51820
}

locals {
  wg_base_ip = "10.200.0"
}

# Build peer block content for each node
locals {
  peer_blocks = {
    for k, v in var.nodes : k => join("\n", [
      for kk, vv in var.nodes : kk != k ? <<-PEER
[Peer]
PublicKey  = <PUBKEY_${kk}>
Endpoint   = ${vv.ip}:${var.wireguard_port}
AllowedIPs  = ${local.wg_base_ip}.${index(keys(var.nodes), kk) + 1}/32
PersistentKeepalive = 25
PEER
      : ""
    ])
  }
}

resource "local_file" "wg_interface" {
  for_each  = var.nodes
  filename  = "${path.module}/wg-${each.key}.conf"
  content   = <<-EOT
# WireGuard config — ${each.key} (${each.value.role})
# Auto-generated by Terraform

[Interface]
Address    = ${local.wg_base_ip}.${index(keys(var.nodes), each.key) + 1}/32
PrivateKey = <PRIVATE_KEY_${each.key}>
ListenPort = ${var.wireguard_port}

# Peers
${local.peer_blocks[each.key]}
EOT
}

resource "local_file" "amnezia_service" {
  for_each  = var.nodes
  filename  = "${path.module}/amnezia-${each.key}.service"
  content   = <<-EOT
[Unit]
Description=AmneziaWG peer ${each.key}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/amneziawg-client install ${local.wg_base_ip}.${index(keys(var.nodes), each.key) + 1}:${var.wireguard_port}
ExecStop=/usr/local/bin/amneziawg-client stop

[Install]
WantedBy=multi-user.target
EOT
}

output "wg_base_ip" {
  value = "${local.wg_base_ip}.0/24"
}
