#!/usr/bin/env bash
# scripts/release.sh — version-aware release helper
# Usage: ./scripts/release.sh [patch|minor|major] [--dry-run]
#
# Does:
#   1. Read current version from pyproject.toml
#   2. Compute new version (patch/minor/major bump)
#   3. Sanity-check: working tree clean
#   4. Pre-release checks: architecture linter, smoke tests
#   5. Bump version in pyproject.toml
#   6. Update CHANGELOG.md (insert new section after [Unreleased])
#   7. Commit + tag v<version>
#   8. Push (or print commands in --dry-run mode)
#
# Required: git, python3. Optional: gh, pytest.

set -euo pipefail

MODE="${1:-patch}"
DRY_RUN="false"
if [[ "${2:-}" == "--dry-run" ]] || [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN="true"
    if [[ "$MODE" == "--dry-run" ]]; then MODE="patch"; fi
fi

if [[ "$MODE" != "patch" && "$MODE" != "minor" && "$MODE" != "major" ]]; then
    echo "Usage: $0 [patch|minor|major] [--dry-run]" >&2
    exit 64
fi

cd "$(git rev-parse --show-toplevel)"

# 1. Read current version
CURRENT="$(python3 -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")"
echo "Current version: $CURRENT"
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
case "$MODE" in
    major) MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0 ;;
    minor) MINOR=$((MINOR+1)); PATCH=0 ;;
    patch) PATCH=$((PATCH+1)) ;;
esac
NEW="${MAJOR}.${MINOR}.${PATCH}"
echo "New version:     $NEW"
TAG="v${NEW}"

# 2. Sanity: working tree clean
echo "--- Checking working tree ---"
if ! git diff --quiet HEAD; then
    echo "::error::Working tree is dirty. Commit or stash first." >&2
    git status --short
    exit 1
fi

# 3. Pre-release checks
echo "--- Running architecture linter ---"
python3 scripts/architecture_linter.py

echo "--- Running tests (smoke) ---"
if command -v pytest >/dev/null; then
    pytest -q --tb=line --no-header \
        --ignore=tests/e2e \
        --ignore=tests/ralph_benchmark \
        -p no:cacheprovider 2>&1 | tail -10 || \
        echo "::warning::Some tests failed (review above)"
else
    echo "pytest not installed; skipping"
fi

# 4. Bump version
echo "--- Bumping pyproject.toml -> ${NEW} ---"
NEW_VERSION="$NEW" python3 - <<'PY'
import os, re, pathlib
ver = os.environ["NEW_VERSION"]
p = pathlib.Path("pyproject.toml")
text = p.read_text()
new_text = re.sub(
    r'version\s*=\s*"[0-9]+\.[0-9]+\.[0-9]+"',
    f'version = "{ver}"',
    text,
    count=1,
)
if new_text == text:
    raise SystemExit("No version field matched in pyproject.toml")
p.write_text(new_text)
PY

# 5. Update CHANGELOG.md
CHANGELOG="CHANGELOG.md"
if [[ -f "$CHANGELOG" ]] && ! grep -q "## \[${NEW}\]" "$CHANGELOG"; then
    echo "--- Adding ${NEW} section to CHANGELOG.md ---"
    NEW_VERSION="$NEW" python3 - <<'PY'
import os, pathlib, datetime
ver = os.environ["NEW_VERSION"]
p = pathlib.Path("CHANGELOG.md")
text = p.read_text()
header = f"## [{ver}] - {datetime.date.today().isoformat()}"
lines = text.splitlines(keepends=True)
out = []
inserted = False
for ln in lines:
    out.append(ln)
    if not inserted and ln.lstrip().startswith("## [Unreleased]"):
        out.append("\n")
        out.append(f"{header}\n")
        out.append("### Added\n- TBD\n\n")
        out.append("### Changed\n- TBD\n\n")
        out.append("### Fixed\n- TBD\n")
        inserted = True
if not inserted:
    body = f"{header}\n### Added\n- TBD\n\n### Changed\n- TBD\n\n### Fixed\n- TBD\n\n" + text
    p.write_text(body)
else:
    p.write_text("".join(out))
PY
else
    echo "(no CHANGELOG.md or section already present)"
fi

# 6. Commit + tag
echo "--- Committing + tagging ---"
git add pyproject.toml CHANGELOG.md
git commit -m "chore(release): v${NEW}" -m "Auto-generated by scripts/release.sh (mode=${MODE})"
git tag -a "${TAG}" -m "Release ${TAG}"

if $DRY_RUN; then
    echo ""
    echo "DRY RUN: did not push. To push:"
    echo "  git push origin HEAD:main"
    echo "  git push origin ${TAG}"
    exit 0
fi

echo "--- Pushing ---"
git push origin HEAD:main
git push origin "${TAG}"

if command -v gh >/dev/null; then
    echo "--- Creating GitHub release ---"
    gh release create "${TAG}" \
        --title "${TAG}" \
        --generate-notes \
        --latest || true
fi

echo ""
echo "Released ${TAG}"
