name: Decrypt secrets and test
on:
  push:
    branches: [ main, develop, 'feat/*' ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install age and sops
        run: |
          sudo apt update
          sudo apt install age -y
          wget https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.amd64 -O /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
      - name: Decrypt secrets
        env:
          AGE_KEY: ${{ secrets.AGE_KEY }}
        run: |
          echo "$AGE_KEY" > age.key
          sops decrypt config/secrets.secret.yaml > config/secrets.yaml
          rm age.key
      - name: Run tests
        run: |
          pytest --no-cov -v
